Delete provide email modal for password changing from settings and add timer
Softjey/react_Examix pull request #75
Opened 2024-06-13 14:38 UTC by Daniel3886

2024-06-14 16:21 UTC, Softjey commented
@Junk-debug Test this feature. Make code review

2024-06-15 11:31 UTC, Junk-debug requested changes

2024-06-15 11:31 UTC, Junk-debug commented on client/src/services/Router/router.tsx
> -import CreateTestPage from '../../pages/CreateTestPage/CreateTestPage';
why did you swapped imports?

2024-06-15 11:31 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +  const [snackbarSeverity, setSnackbarSeverity] = useState<'success' | 'error'>('success');
we have component for this - ErrorSnackBar

2024-06-15 11:31 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +      <Snackbar open={snackbarOpen} autoHideDuration={6000} onClose={handleClose}>
also you can move it to separate component - SucessSnackbar or smth like this

2024-06-15 11:31 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +      <Snackbar open={snackbarOpen} autoHideDuration={6000} onClose={handleClose}>
dont use snakbarOpen state, snakbar cant be opened when message is null, so delete this state, you can just add check snackBarMessage !== null

2024-06-15 11:31 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +  const [snackbarMessage, setSnackbarMessage] = useState<string>('');
make it nullable, and set inital value to null, when snackBar message equals null, snackbar is closed

2024-06-15 11:31 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +            'Password reset email sent successfully. If you want to change again, please wait for 1 minute.',
'Password reset email sent successfully.' is enough

2024-06-15 11:31 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +    setSnackbarOpen(false);
here you set snackbarMessage to null

2024-06-15 11:31 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +    setTimer(60);
you should set timer only when email was sent successfully, when request is pending you should show loading, you can use loading Button for this
<img width="156" alt="Screenshot 2024-06-15 at 13 26 19" src="https://github.com/Softjey/react_Examix/assets/77940841/51b4e419-a3ca-4f1a-9e91-c11ad1338182">
this should not be displayed until email sent successfully

2024-06-15 19:11 UTC, Junk-debug requested changes

2024-06-15 19:11 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +        <Alert elevation={1} variant="standard" onClose={handleClose} severity={snackbarSeverity}>
dont use elevation here

2024-06-15 19:11 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
>            setDisableButton(false);
why this is needed?
you dont set button to disable when request starts

2024-06-15 19:11 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +      <Snackbar open={snackbarMessage !== null} onClose={handleClose} autoHideDuration={6000}>
make hide duration to 3000

2024-06-15 19:11 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +      <Snackbar open={snackbarMessage !== null} onClose={handleClose} autoHideDuration={6000}>
you dont need to create separate handleClose function, you can use arrow function here

2024-06-16 10:15 UTC, Softjey commented
@Junk-debug Test this feature and make review again

2024-06-16 15:28 UTC, Junk-debug requested changes

2024-06-16 15:28 UTC, Junk-debug commented on client/src/components/ChangePassword.tsx
> +        <Alert variant="standard" onClose={handleClose} severity={snackbarSeverity}>
dont use handleClose function here, just () => setSnackbarMessage(null)

2024-06-16 23:23 UTC, Softjey commented on client/src/components/ChangePassword.tsx
> +        <Alert variant="standard" onClose={handleClose} severity={snackbarSeverity}>
It's not so important

2024-06-16 23:23 UTC, Softjey commented
@Junk-debug This feature already fully work?

2024-06-16 23:57 UTC, Junk-debug commented
<img width="910" alt="image" src="https://github.com/Softjey/react_Examix/assets/77940841/d71d72c4-3fab-4ba7-a972-d9ca1e343809">
i dont know why, but snackbar doesnt hide automatically, you can see at timer

2024-06-17 11:18 UTC, Junk-debug approved these changes

2024-06-17 11:19 UTC, Junk-debug commented
@Softjey, pull request has been tested and reviewed

2024-06-17 14:08 UTC, Softjey commented on client/src/components/ChangePassword.tsx
> +  }, [disableButton, timer]);
You create new Interval on every timer change, because you have timer in useEffect deps array. Refactor this, it's a bad solution. Hint for you is Timer component. Check its logic. @Junk-debug Help @Daniel3886 to do this.

Also i strongly recommend separate timer logic from timer component to custom useTimer hook. And you use it here, and in Timer component

2024-06-17 14:08 UTC, Softjey commented on client/src/components/ChangePassword.tsx
> +      },
user?.email || '', - make user null check instead of this bug.

2024-06-17 14:08 UTC, Softjey commented on client/src/components/ChangePassword.tsx
> +        redirectUrl: `${window.location.href.split('#')[0]}#/reset-password`,
redirectUrl: `${window.location.href.split('#')[0]}#/reset-password`,

/reset-password have to be into Routes enum.

Also don't use window.location.href, try to way use react router dom solution

2024-06-17 14:08 UTC, Softjey commented on client/src/components/ChangePassword.tsx
> +      </Snackbar>
use ErrorSnackBar component instead

2024-06-17 14:08 UTC, Softjey commented on client/src/services/Router/router.tsx
> -import CreateTestPage from '../../pages/CreateTestPage/CreateTestPage';
This is not resolved conversation. Don't swap imports

2024-06-23 21:12 UTC, merged